services:
  - type: web
    name: aaexpense
    env: python
    branch: main
    buildCommand: bash build.sh
    startCommand: cd project && gunicorn project.wsgi:application
    pythonVersion: "3.14"
