services:
  - type: web
    name: aaexpense
    env: python
    branch: main
    rootDirectory: project
    buildCommand: pip install -r ../requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn project.wsgi:application
    pythonVersion: "3.14"
services:
  - type: web
    name: aaexpense
    env: python
    branch: main
    rootDirectory: project
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn project.wsgi:application
    pythonVersion: "3.14"
