# Generated by Django 6.0.2 on 2026-03-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('entertainment', 'Entertainment'), ('grocery', 'Grocery'), ('food', 'Food'), ('stationery', 'Stationery'), ('transport', 'Transport'), ('health', 'Health'), ('rent', 'Rent'), ('education', 'Education'), ('bills', 'Bills'), ('shopping', 'Shopping'), ('others', 'Others')], default='others', max_length=80),
        ),
    ]
