# Generated by Django 6.0.2 on 2026-04-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_alter_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('credit_card', 'Credit Card'), ('credit_card_bill', 'Credit Card Bill Payment')], default='upi', max_length=20),
        ),
    ]
